import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import PostList from '../ui/components/PostList/PostList'
import styles from '../ui/styles/Home.module.css'
import useIndex from '../data/hooks/pages/useIndex.page'

const Home: NextPage = () => {
  const {posts} = useIndex()

  return (
    <div>
      <Head>
        <title>Lucas Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PostList posts={posts}/>
      </main>

    </div>
  )
}

export default Home
